# Generated by Django 5.2.1 on 2025-06-03 18:47

import core.models_validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("paused", "paused")],
                        max_length=6,
                        verbose_name="status",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[core.models_validators.campaign_budget_validator],
                        verbose_name="budget",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("finish_date", models.DateField(verbose_name="finish date")),
                (
                    "last_update",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="last update published in the campaign",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "get_latest_by": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="image"
                    ),
                ),
                (
                    "header",
                    models.TextField(blank=True, null=True, verbose_name="header"),
                ),
                ("body", models.TextField(verbose_name="body")),
                (
                    "footer",
                    models.TextField(blank=True, null=True, verbose_name="footer"),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "get_latest_by": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("administrator", "Administrator"),
                            ("publisher", "Publisher"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("name", models.CharField(max_length=250, verbose_name="name")),
                (
                    "tg_id",
                    models.TextField(blank=True, null=True, verbose_name="tg id"),
                ),
                ("is_bot_installed", models.BooleanField(verbose_name="bot installed")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="active"),
                ),
                ("meta", models.JSONField(blank=True, null=True, verbose_name="meta")),
                (
                    "last_update",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="last update published in the channel",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "publisher"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "get_latest_by": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CampaignChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "cpm",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="views price"
                    ),
                ),
                (
                    "impressions_plan",
                    models.IntegerField(verbose_name="planed views count"),
                ),
                (
                    "impressions_fact",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="fact views count"
                    ),
                ),
                (
                    "is_message_published",
                    models.BooleanField(
                        default=False, verbose_name="is message published in th channel"
                    ),
                ),
                (
                    "message_publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="message published date"
                    ),
                ),
                ("channel_post_id", models.TextField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns_channel",
                        to="core.campaign",
                        verbose_name="campaign",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_campaigns",
                        to="core.channel",
                        verbose_name="channel",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_campaigns",
                        to="core.message",
                        verbose_name="message",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "get_latest_by": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="channels",
            field=models.ManyToManyField(
                through="core.CampaignChannel", to="core.channel"
            ),
        ),
        migrations.CreateModel(
            name="ChannelTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("title", models.CharField(verbose_name="title")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "get_latest_by": [
                    models.OrderBy(
                        models.F("created_at"), descending=True, nulls_last=True
                    ),
                    models.OrderBy(
                        models.F("updated_at"), descending=True, nulls_last=True
                    ),
                ],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("title", models.TextField(verbose_name="link title")),
                ("url", models.URLField(verbose_name="url")),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("info", "information"),
                            ("image", "image"),
                            ("video", "video"),
                            ("other", "other"),
                        ],
                        default="info",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "unique_together": {("message", "position")},
            },
        ),
    ]
