# Generated by Django 5.2.1 on 2025-06-10 18:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Message.image_path, verbose_name='image'),
        ),
    ]
