# Generated by Django 5.2.1 on 2025-06-12 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_message_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="message",
            name="footer",
        ),
        migrations.RemoveField(
            model_name="message",
            name="header",
        ),
        migrations.AddField(
            model_name="user",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owners",
                to="core.channel",
            ),
        ),
    ]
