# Generated by Django 5.2.1 on 2025-06-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_campaign_last_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("paused", "paused")],
                default="paused",
                max_length=6,
                verbose_name="status",
            ),
        ),
    ]
