# Generated by Django 5.2.1 on 2025-06-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
    ]
