# Generated by Django 5.2.1 on 2025-06-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_campaign_channel_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='channel_post_id',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_message_published',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='message_publish_date',
        ),
        migrations.AddField(
            model_name='message',
            name='channel_post_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_message_published',
            field=models.BooleanField(default=False, verbose_name='is message published in th channel'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='message published date'),
        ),
    ]
