# Generated by Django 5.2.1 on 2025-06-16 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_messagelink_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagelink",
            name="position",
        ),
        migrations.RemoveField(
            model_name="messagelink",
            name="type",
        ),
    ]
