# Generated by Django 5.2.1 on 2025-06-18 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_alter_channel_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="avatar",
            new_name="avatar_url",
        ),
    ]
