# Generated by Django 5.2.1 on 2025-06-29 00:53

import core.models
import core.models_validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_channel_geo_channel_members_count_channel_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignchannel',
            name='publish_status',
            field=models.CharField(blank=True, choices=[('planned', 'запланировано'), ('published', 'опубликовано'), ('deleted', 'удалённо')], default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='avg_post_coverage',
            field=models.PositiveIntegerField(default=0, verbose_name='Ср.рек.охват 1 поста'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[core.models_validators.campaign_budget_validator], verbose_name='Бюджет (руб.)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='finish_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('paused', 'paused')], default='paused', max_length=6, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='campaignchannel',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_channel', to='core.campaign', verbose_name='Кампания'),
        ),
        migrations.AlterField(
            model_name='campaignchannel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_campaigns', to='core.channel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='campaignchannel',
            name='cpm',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='СРМ (руб.)'),
        ),
        migrations.AlterField(
            model_name='campaignchannel',
            name='impressions_fact',
            field=models.IntegerField(default=0, verbose_name='Показы-факт'),
        ),
        migrations.AlterField(
            model_name='campaignchannel',
            name='impressions_plan',
            field=models.IntegerField(default=0, help_text='рассчитывается как (Бюджет/СРМ)*1000', verbose_name='План. Количество показов'),
        ),
        migrations.AlterField(
            model_name='campaignchannel',
            name='is_message_published',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='campaignchannel',
            name='message_publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='geo',
            field=models.CharField(blank=True, choices=[('Choice_1', 'choice_1'), ('Choice_2', 'choice_2'), ('Choice_3', 'choice_3')], max_length=10, null=True, verbose_name='Гео'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='invitation_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='ссылка-приглашение'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='is_bot_installed',
            field=models.BooleanField(default=False, verbose_name='Бот'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число подписчиков'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='meta',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='meta'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subject',
            field=models.CharField(blank=True, choices=[('Choice_1', 'choice_1'), ('Choice_2', 'choice_2'), ('Choice_3', 'choice_3')], max_length=10, null=True, verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='тело'),
        ),
        migrations.AlterField(
            model_name='message',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.messagelink', verbose_name='кнопка'),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.Message.image_path, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=core.models.Message.image_path, verbose_name='видео'),
        ),
        migrations.AlterField(
            model_name='messagelink',
            name='title',
            field=models.TextField(verbose_name='название ссылки'),
        ),
        migrations.AlterField(
            model_name='messagelink',
            name='url',
            field=models.URLField(verbose_name='URL-адрес'),
        ),
    ]
