# Generated by Django 5.2.1 on 2025-06-29 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_campaignchannel_publish_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Кампания",
                "verbose_name_plural": "Кампании",
            },
        ),
        migrations.AlterModelOptions(
            name="campaignchannel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Кампания-Канал",
                "verbose_name_plural": "Кампании-Каналы",
            },
        ),
        migrations.AlterModelOptions(
            name="channel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Канал",
                "verbose_name_plural": "Каналы",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="messagelink",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ссылка",
                "verbose_name_plural": "ссылки",
            },
        ),
    ]
