# Generated by Django 5.2.1 on 2025-06-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_campaign_options_alter_campaignchannel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
