# Generated by Django 5.2.1 on 2025-06-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_campaignchannel_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignchannel',
            name='publish_status',
            field=models.CharField(choices=[('planned', 'запланировано'), ('published', 'опубликовано'), ('deleted', 'удалённо')], default='planned', max_length=30, verbose_name='Статус публикации'),
        ),
    ]
