# Generated by Django 5.2.1 on 2025-06-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_alter_campaignchannel_publish_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignchannel",
            name="clicks",
            field=models.PositiveIntegerField(
                default=0, help_text="clicks by users on the campaign"
            ),
        ),
    ]
