# Generated by Django 5.2.1 on 2025-06-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_channeladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeladmin',
            name='cooperation_form',
            field=models.CharField(choices=[('legal', 'ФЛ (без статуса СЗ)'), ('c3', 'СЗ'), ('entrepreneur', 'ИП')], default='legal', max_length=50),
        ),
    ]
