# Generated by Django 5.2.1 on 2025-06-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_channeladmin_cooperation_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeladmin',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец канала'), ('manager', 'Менеджер')], default='manager', max_length=50),
        ),
    ]
