# Generated by Django 5.2.1 on 2025-06-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_channeladmin_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channeladmin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Админ', 'verbose_name_plural': 'Админы'},
        ),
        migrations.AddField(
            model_name='channeladmin',
            name='channels',
            field=models.ManyToManyField(related_name='admins', to='core.channel', verbose_name='Каналы'),
        ),
        migrations.DeleteModel(
            name='ChannelTag',
        ),
    ]
