# Generated by Django 5.2.1 on 2025-06-30 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_channeladmin_options_channeladmin_channels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignchannel",
            name="channel_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_campaigns",
                to="core.channeladmin",
                verbose_name="Админ",
            ),
        ),
    ]
