# Generated by Django 5.2.1 on 2025-06-30 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_channeladmin_tg_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channeladmin",
            old_name="tg_username",
            new_name="username",
        ),
    ]
