# Generated by Django 5.2.1 on 2025-06-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_channeladmin_is_bot_installed"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignchannel",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Одобрено"),
        ),
    ]
