# Generated by Django 5.2.1 on 2025-07-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_campaign_inn_advertiser_campaign_token_ord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignchannel",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Разрешено"),
        ),
    ]
