# Generated by Django 5.2.1 on 2025-07-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_campaign_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='avg_posts_reach',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Охват'),
        ),
        migrations.AddField(
            model_name='channel',
            name='er',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='ER'),
        ),
        migrations.AddField(
            model_name='channel',
            name='err',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='ERR'),
        ),
        migrations.AddField(
            model_name='channel',
            name='err_24',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='ERR24'),
        ),
    ]
