# Generated by Django 5.2.1 on 2025-07-05 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_remove_channel_geo_channel_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="subject",
            new_name="category",
        ),
    ]
