# Generated by Django 5.2.1 on 2025-07-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_rename_subject_channel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='daily_reach',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='daily reach'),
        ),
        migrations.AddField(
            model_name='channel',
            name='posts_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='posts count'),
        ),
    ]
