# Generated by Django 5.2.1 on 2025-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_channel_about_channel_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="country",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Страна"
            ),
        ),
    ]
