# Generated by Django 5.2.1 on 2025-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_channel_about_alter_channel_daily_reach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='about',
            field=models.TextField(blank=True, default=0, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='language',
            field=models.CharField(blank=True, default=0, verbose_name='Язык'),
        ),
    ]
