# Generated by Django 5.2.1 on 2025-07-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_channel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='avg_post_coverage',
        ),
    ]
