# Generated by Django 5.2.1 on 2025-07-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_channeladmin_user_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channeladmin",
            name="role",
            field=models.CharField(
                choices=[("owner", "Владелец канала"), ("manager", "Менеджер Системы")],
                default="owner",
                max_length=50,
            ),
        ),
    ]
