# Generated by Django 5.2.1 on 2025-07-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_message_name_alter_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='button_str',
            field=models.CharField(blank=True, default='Click Me!', max_length=250),
        ),
    ]
