# Generated by Django 5.2.1 on 2025-07-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_alter_message_button"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="button_link",
            field=models.URLField(blank=True, null=True, verbose_name="URL-адрес"),
        ),
        migrations.AlterField(
            model_name="message",
            name="button_str",
            field=models.CharField(
                blank=True,
                default="Click Me!",
                max_length=250,
                verbose_name="название ссылки",
            ),
        ),
    ]
