# Generated by Django 5.2.1 on 2025-07-13 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_alter_message_button_link_alter_message_button_str"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="button",
        ),
    ]
