# Generated by Django 5.2.1 on 2025-07-14 22:08

from django.db import migrations


def on_commit(apps, schema):
    "remove all empty campaigns"
    Campaign = apps.get_model('core', 'Campaign')
    Campaign.objects.filter(message__isnull=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_channeladmin_tg_id'),
    ]

    operations = [
        migrations.RunPython(on_commit, migrations.RunPython.noop),
    ]
