# Generated by Django 5.2.1 on 2025-07-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20250714_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.message', verbose_name='message'),
        ),
    ]
