# Generated by Django 5.2.1 on 2025-07-14 23:03

from django.db import migrations


def on_commit(apps, schema):
    CampaignChannel = apps.get_model('core', 'CampaignChannel')
    CampaignChannel.objects.filter(channel_admin__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_campaignchannel_channel_admin'),
    ]

    operations = [
        migrations.RunPython(on_commit, migrations.RunPython.noop),
    ]
