# Generated by Django 5.2.1 on 2025-07-17 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_campaignchannel_channel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignchannel',
            name='channel_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_campaigns', to='core.channeladmin', verbose_name='Админ'),
        ),
    ]
