# Generated by Django 5.2.1 on 2025-07-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_alter_campaignchannel_channel_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="category",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Тематика"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="country",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Страна"
            ),
        ),
    ]
