# Generated by Django 5.2.1 on 2025-07-20 20:24

from django.db import migrations

from web_app.logger import logger


def on_commit(apps, schema):
    ChannelAdmin = apps.get_model('core', 'ChannelAdmin')
    Group = apps.get_model('auth', 'Group')
    channel_admins = ChannelAdmin.objects.filter(user__isnull=True)
    User = apps.get_model('core', 'User')
    logger.info(f'found {len(channel_admins)} channel admins')
    for channel_admin in channel_admins:
        logger.info(f'{channel_admin=} in process.')
        user = User.objects.filter(username=channel_admin.username).first()
        if not user:
            user = User.objects.create_user(
                username=channel_admin.username,
                password=channel_admin.username +'123123456',
                profile=channel_admin,
                first_name=channel_admin.first_name,
                last_name=channel_admin.last_name,
                is_active=True,
                is_staff=True,
            )
        else:
            user.username = channel_admin.username
            user.first_name = channel_admin.first_name
            user.last_name = channel_admin.last_name
            user.is_active = True
            user.is_staff = True
            user.save()

        user.groups.clear()
        user.groups.add(Group.objects.get(name=channel_admin.role))
        logger.info(f'{channel_admin=} Done.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_remove_user_channel_remove_user_tg_id_and_more'),
    ]

    operations = [
        migrations.RunPython(on_commit, migrations.RunPython.noop),
    ]
