# Generated by Django 5.2.1 on 2025-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_auto_20250720_2024"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_stats",
            field=models.BooleanField(default=True),
        ),
    ]
