# Generated by Django 5.2.1 on 2025-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_message_is_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="is_stats",
            field=models.BooleanField(default=True, verbose_name="отслеживать клики?"),
        ),
    ]
