# Generated by Django 5.2.1 on 2025-07-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_message_is_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_stats',
            field=models.BooleanField(default=False, verbose_name='Ссылка на канал телеграм?'),
        ),
    ]
