# Generated by Django 5.2.1 on 2025-07-31 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_alter_message_is_stats"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="is_stats",
            new_name="is_external",
        ),
    ]
