# Generated by Django 5.2.5 on 2025-09-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_channel_cpm"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="brand",
            field=models.CharField(default="", help_text="Бренд", verbose_name="Бренд"),
        ),
    ]
