# Generated by Django 5.2.5 on 2025-09-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_campaign_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="channels",
            field=models.ManyToManyField(
                blank=True, through="core.CampaignChannel", to="core.channel"
            ),
        ),
    ]
