# Generated by Django 5.2.5 on 2025-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0095_channel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На модерации"),
                    ("confirmed", "Подтверждено"),
                    ("rejected", "Отказано"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
