# Generated by Django 5.2.5 on 2025-09-02 18:44

from django.db import migrations
from django.db.models import When, Case, Q, Value


def on_commit(apps, schema):
    """Add default status for old channels """

    Channel = apps.get_model('core.Channel')
    Channel.objects.update(
        status=Case(
            When(condition=Q(is_active=True), then=Value('confirmed')),
            default=Value('pending'),
        )
    )


def rollback(apps, schema):
    """Runs on downgrade"""
    Channel = apps.get('core.Channel')
    Channel.objects.update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_channel_status'),
    ]

    operations = [
        migrations.RunPython(
            on_commit,
            rollback
        )
    ]
