# Generated by Django 5.2.5 on 2025-09-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_update_channel_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='is_active',
        ),
    ]
