# Generated by Django 5.2.5 on 2025-09-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0098_remove_channel_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignchannel",
            name="publish_status",
            field=models.CharField(
                choices=[
                    ("planned", "Ожидает подтверждения"),
                    ("published", "опубликовано"),
                    ("deleted", "удалённо"),
                ],
                default="planned",
                max_length=30,
                verbose_name="Статус публикации",
            ),
        ),
    ]
