# Generated by Django 5.2.5 on 2025-09-02 19:56

from django.db import migrations
from django.db.models import When, Case, Q, Value, F


def on_commit(apps, schema):
    """Update publish status to have the old status from other fields, that will be deleted."""
    CampaignChannel = apps.get_model('core', 'CampaignChannel')
    CampaignChannel.objects.update(publish_status=
    Case(
        When(Q(is_message_published=True, is_approved=True) | Q(message_publish_date__isnull=False), then=Value('published')),
        When(Q(is_approved=True) & Q(Q(is_message_published=False) | Q(message_publish_date__isnull=True)), then=Value('confirmed')),
        When(Q(is_approved=False, is_message_published=False), then=Value('planned')),
        default=F('publish_status')
    ))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_campaignchannel_publish_status'),
    ]

    operations = [
        migrations.RunPython(on_commit, migrations.RunPython.noop),
    ]
