# Generated by Django 5.2.5 on 2025-09-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_update_publish_status_new_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignchannel',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='campaignchannel',
            name='is_message_published',
        ),
    ]
