# Generated by Django 5.2.5 on 2025-09-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_remove_campaignchannel_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='is_bot_installed',
            field=models.BooleanField(default=False, help_text='Бот установлен', verbose_name='Бот ТЕЛЕВИН'),
        ),
    ]
