# Generated by Django 5.2.5 on 2025-09-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_message_ad_individual_message_ad_inn_message_erd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='erd',
        ),
        migrations.AddField(
            model_name='message',
            name='erid',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='ERID'),
        ),
    ]
