# Generated by Django 5.2.5 on 2025-09-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_remove_message_erd_message_erid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Креатив', 'verbose_name_plural': 'Креативы'},
        ),
    ]
