# Generated by Django 5.2.5 on 2025-09-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
