# Generated by Django 5.2.5 on 2025-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='members_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Подписчики'),
        ),
    ]
