# Generated by Django 5.2.5 on 2025-09-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alter_user_options_alter_channel_members_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignchannel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистики'},
        ),
    ]
