# Generated by Django 5.2.5 on 2025-09-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_campaignchannel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignchannel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
