# Generated by Django 5.2.5 on 2025-09-09 13:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_alter_campaignchannel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignchannel',
            name='plan_cpm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='План. CPM'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='black_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, help_text='разделитель , (если пусто то не будет фильтровать)', size=None, verbose_name='запрещённые слова'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='white_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, help_text='разделитель , (если пусто то не будет фильтровать)', size=None, verbose_name='разрешённые слова'),
        ),
    ]
