# Generated by Django 5.2.5 on 2025-09-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_campaignchannel_plan_cpm_alter_campaign_black_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignchannel',
            name='publish_status',
            field=models.CharField(choices=[('agreement', 'На согласовании'), ('planned', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('published', 'опубликовано'), ('deleted', 'удалённо'), ('rejected', 'Отклонено')], default='planned', max_length=30, verbose_name='Статус публикации'),
        ),
    ]
