# Generated by Django 5.2.5 on 2025-09-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_alter_campaignchannel_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='client',
            field=models.CharField(blank=True, default='', help_text='Клиент', verbose_name='Рекламодатель'),
        ),
    ]
