# Generated by Django 5.2.5 on 2025-09-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_alter_campaign_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('paused', 'На паузе')], default='paused', max_length=6, verbose_name='Статус'),
        ),
    ]
