# Generated by Django 5.2.5 on 2025-09-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_alter_campaign_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='finish_date',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
    ]
