# Generated by Django 5.2.5 on 2025-09-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_alter_campaign_finish_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignchannel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
