# Generated by Django 5.2.5 on 2025-09-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_campaignchannel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar_url',
            field=models.URLField(blank=True, default='/static/custom/default.jpg', null=True, verbose_name='avatar'),
        ),
    ]
