# Generated by Django 5.2.6 on 2025-09-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_alter_channel_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignchannel',
            name='cpm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='СРМ (руб.)'),
        ),
    ]
