# Generated by Django 5.2.6 on 2025-09-22 08:44

from django.db import migrations

def end(apps, schema):
    User = apps.get_model('core', 'User')
    ChannelAdmin = apps.get_model('core', 'ChannelAdmin')
    users_no_profile = User.objects.filter(
        is_superuser=False,
        profile__isnull=True,
        groups__isnull=False,
    )
    channel_admins = []
    for user in users_no_profile:
        group = user.groups.first()
        print(f'To Create ChannelAdmin as {group.name} - {user.username}')
        profile = ChannelAdmin(
            user=user,
            username=user.username,
            first_name=user.first_name,
            last_name=user.last_name,
            tg_id=user.username,
            role=group.name,
        )
        channel_admins.append(profile)
    ChannelAdmin.objects.bulk_create(channel_admins)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_alter_campaignchannel_cpm'),
    ]

    operations = [
        migrations.RunPython(end, migrations.RunPython.noop),
    ]
