# Generated by Django 5.2.7 on 2025-10-24 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_campaign_and_message_formats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='format',
            field=models.CharField(choices=[('sponsorship', 'Спонсорство'), ('fixed_slot', 'Фикс-слот'), ('autopilot', 'Автопилот')], default='autopilot', max_length=32, verbose_name='Формат размещения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='format',
            field=models.CharField(choices=[('sponsorship', 'Спонсорство'), ('fixed_slot', 'Фикс-слот'), ('autopilot', 'Автопилот')], default='autopilot', max_length=32, verbose_name='Формат размещения'),
        ),
        migrations.CreateModel(
            name='ChannelPublicationSlot',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_slots', to='core.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Доступный слот публикации',
                'verbose_name_plural': 'Доступные слоты публикации',
                'ordering': ['channel', 'weekday', 'start_time'],
                'unique_together': {('channel', 'weekday', 'start_time', 'end_time')},
            },
        ),
    ]
