# Generated by Django 5.2.7 on 2025-10-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_alter_campaign_format_alter_message_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignchannel',
            name='publication_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_channels', to='core.channelpublicationslot', verbose_name='Слот публикации'),
        ),
    ]
