# Generated by Django 5.2.7 on 2025-10-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_campaignchannel_publication_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='require_manual_approval',
            field=models.BooleanField(default=False, help_text='Если включено, владелец канала должен вручную подтверждать каждую публикацию', verbose_name='Требует ручного подтверждения'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='format',
            field=models.CharField(choices=[('sponsorship', 'Спонсорство'), ('fixed_slot', 'Фикс-слот'), ('autopilot', 'Автопилот')], default='fixed_slot', max_length=32, verbose_name='Формат размещения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='format',
            field=models.CharField(choices=[('sponsorship', 'Спонсорство'), ('fixed_slot', 'Фикс-слот'), ('autopilot', 'Автопилот')], default='fixed_slot', max_length=32, verbose_name='Формат размещения'),
        ),
    ]
