# Generated by Django 5.2.7 on 2025-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0129_userlogintoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("active", "Активна"),
                    ("paused", "На паузе"),
                ],
                default="draft",
                max_length=6,
                verbose_name="Статус",
            ),
        ),
    ]
