# Generated by Django 5.2.7 on 2025-11-18 07:26

import django_prometheus.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_add_campaign_draft_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='Полное наименование организации', max_length=500, verbose_name='Название юридического лица')),
                ('short_name', models.CharField(blank=True, default='', max_length=250, verbose_name='Сокращённое название')),
                ('inn', models.CharField(help_text='10 цифр для юрлиц, 12 для ИП', max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, default='', help_text='Код причины постановки на учёт', max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, default='', help_text='Основной государственный регистрационный номер', max_length=15, verbose_name='ОГРН/ОГРНИП')),
                ('legal_address', models.TextField(blank=True, default='', verbose_name='Юридический адрес')),
                ('bank_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Название банка')),
                ('bank_bik', models.CharField(blank=True, default='', help_text='Банковский идентификационный код', max_length=9, verbose_name='БИК банка')),
                ('bank_correspondent_account', models.CharField(blank=True, default='', max_length=20, verbose_name='Корреспондентский счёт')),
                ('bank_account', models.CharField(blank=True, default='', max_length=20, verbose_name='Расчётный счёт')),
                ('contact_person', models.CharField(blank=True, default='', max_length=250, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Контактный email')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('pending', 'На модерации'), ('suspended', 'Приостановлено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, default='', help_text='Внутренние заметки', verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
                'ordering': ['-created_at'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('legalentity'), models.Model),
        ),
    ]
