# Generated by Django 5.2.7 on 2025-11-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_legalentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignchannel",
            name="approval_notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Уведомление об ожидании"
            ),
        ),
    ]

