# Generated by Django 5.2.7 on 2025-11-18 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_legalentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='legal_entity',
            field=models.ForeignKey(blank=True, help_text='Юридическое лицо, к которому привязан канал', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='core.legalentity', verbose_name='Юридическое лицо'),
        ),
    ]
