# Generated by Django 5.2.7 on 2025-11-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_campaignchannel_approval_notified_at'),
        ('core', '0132_channel_legal_entity'),
    ]

    operations = [
    ]
