# Generated by Django 5.2.7 on 2025-11-18 08:19

import django.db.models.deletion
import django_prometheus.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_merge_20251118_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('transaction_type', models.CharField(choices=[('income', 'Начисление'), ('deduction', 'Удержание'), ('payout', 'Выплата'), ('refund', 'Возврат')], help_text='Тип финансовой операции', max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма операции (положительная для начислений, отрицательная для списаний)', max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', help_text='Код валюты (ISO 4217)', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('completed', 'Завершено'), ('frozen', 'Заморожено'), ('cancelled', 'Отменено')], default='pending', help_text='Статус операции', max_length=20, verbose_name='Статус')),
                ('source_type', models.CharField(blank=True, default='', help_text='Тип источника операции (например: publication, manual, commission)', max_length=50, verbose_name='Тип источника')),
                ('source_id', models.UUIDField(blank=True, help_text='UUID связанного объекта (публикация, кампания, и т.д.)', null=True, verbose_name='ID источника')),
                ('description', models.TextField(blank=True, default='', help_text='Описание операции', verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные в формате JSON', verbose_name='Метаданные')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Дата и время завершения операции', null=True, verbose_name='Дата завершения')),
                ('channel', models.ForeignKey(help_text='Канал, к которому относится операция', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Финансовая операция',
                'verbose_name_plural': 'Финансовые операции',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', '-created_at'], name='core_channe_channel_ef0270_idx'), models.Index(fields=['channel', 'status'], name='core_channe_channel_a2f192_idx'), models.Index(fields=['transaction_type', 'status'], name='core_channe_transac_e5b330_idx')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('channeltransaction'), models.Model),
        ),
    ]
