# Generated by Django 5.2.7 on 2025-11-18 12:30

from django.db import migrations, models


def migrate_buttons(apps, schema_editor):
    Message = apps.get_model("core", "Message")
    for msg in Message.objects.all():
        buttons = []
        if getattr(msg, "button_str", None) and getattr(msg, "button_link", None):
            buttons.append({"text": msg.button_str, "url": msg.button_link})
        msg.buttons = buttons
        msg.save(update_fields=["buttons"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0134_channeltransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="buttons",
            field=models.JSONField(blank=True, default=list, verbose_name="Кнопки"),
        ),
        migrations.RunPython(migrate_buttons, migrations.RunPython.noop),
        migrations.RemoveField(model_name="message", name="button_link"),
        migrations.RemoveField(model_name="message", name="button_str"),
    ]

