# Generated by Django 5.2.7 on 2025-11-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0135_message_buttons"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignchannel",
            name="button_clicks",
            field=models.JSONField(default=dict, blank=True, verbose_name="Клики по кнопкам"),
        ),
    ]

