# Generated by Django 4.2.26 on 2025-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_campaignchannel_clicks_by_button'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='channeltransaction',
            name='core_channe_channel_a2f192_idx',
        ),
        migrations.RemoveIndex(
            model_name='channeltransaction',
            name='core_channe_transac_e5b330_idx',
        ),
        migrations.RemoveField(
            model_name='channeltransaction',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='channeltransaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='channeltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Сумма операции (знак определяет направление: + увеличение, - уменьшение баланса)', max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='channeltransaction',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание операции для audit trail', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='channeltransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Доп. данные (impressions, cpm, и т.д.)', verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='channeltransaction',
            name='source_id',
            field=models.UUIDField(blank=True, help_text='UUID связанного объекта (CampaignChannel, etc.)', null=True, verbose_name='ID источника'),
        ),
        migrations.AlterField(
            model_name='channeltransaction',
            name='source_type',
            field=models.CharField(blank=True, default='', help_text='Тип источника: campaign_channel, manual, system', max_length=50, verbose_name='Тип источника'),
        ),
        migrations.AlterField(
            model_name='channeltransaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Начисление'), ('refund', 'Возврат'), ('unfreeze', 'Разморозка'), ('freeze', 'Заморозка'), ('payout', 'Выплата'), ('commission', 'Комиссия'), ('adjustment', 'Корректировка')], help_text='Тип финансовой операции', max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AddIndex(
            model_name='channeltransaction',
            index=models.Index(fields=['channel', 'transaction_type'], name='core_channe_channel_92d81e_idx'),
        ),
        migrations.AddIndex(
            model_name='channeltransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='core_channe_source__5d624d_idx'),
        ),
    ]
