# Generated by Django 4.2.26 on 2025-11-18 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_remove_transaction_status_for_event_sourcing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Период с')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Период по')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'В обработке'), ('paid', 'Выплачено'), ('canceled', 'Отменено')], default='draft', max_length=10, verbose_name='Статус')),
                ('description', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='core.legalentity', verbose_name='Юрлицо')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
