# Generated by Django 4.2.26 on 2025-11-19 12:47

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_campaign_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('format', models.CharField(choices=[('sponsorship', 'Спонсорство'), ('fixed_slot', 'Фикс-слот'), ('autopilot', 'Автопилот')], max_length=32, verbose_name='Формат размещения')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('success', 'Успешно опубликовано'), ('error', 'Ошибка'), ('no_creative', 'Креатив не найден')], default='pending', max_length=16, verbose_name='Статус')),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Исходные параметры запроса от микросервиса', verbose_name='Данные запроса')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Результат обработки или ошибка', verbose_name='Данные ответа')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('campaign_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_requests', to='core.campaignchannel', verbose_name='Связь кампании с каналом')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_requests', to='core.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Запрос на публикацию',
                'verbose_name_plural': 'Запросы на публикацию',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_public_created_9b9462_idx'), models.Index(fields=['channel', '-created_at'], name='core_public_channel_ae66c6_idx'), models.Index(fields=['status', '-created_at'], name='core_public_status_4e44d2_idx')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('publication_request'), models.Model),
        ),
    ]
