# Generated by Django 4.2.26 on 2025-11-19 13:24

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_add_publication_request_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('account_type', models.CharField(choices=[('cash', 'Касса'), ('frozen', 'Заморожено'), ('revenue', 'Выручка'), ('expense', 'Расходы')], help_text='Тип счёта в системе двойной записи', max_length=20, verbose_name='Тип счёта')),
                ('currency', models.CharField(default='RUB', help_text='Код валюты (ISO 4217)', max_length=3, verbose_name='Валюта')),
                ('channel', models.ForeignKey(help_text='Канал, к которому относится счёт', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['channel', 'account_type'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('account'), models.Model),
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Сумма записи (всегда положительная)', max_digits=10, verbose_name='Сумма')),
                ('entry_type', models.CharField(choices=[('debit', 'Дебет'), ('credit', 'Кредит')], help_text='Дебет или Кредит', max_length=10, verbose_name='Тип записи')),
                ('transaction_id', models.UUIDField(db_index=True, help_text='UUID для группировки парных записей (debit + credit)', verbose_name='ID транзакции')),
                ('transaction_type', models.CharField(choices=[('income', 'Начисление дохода'), ('freeze', 'Заморозка средств'), ('unfreeze', 'Разморозка средств'), ('payout', 'Выплата'), ('commission', 'Комиссия'), ('refund', 'Возврат'), ('adjustment', 'Корректировка')], help_text='Тип бизнес-операции', max_length=20, verbose_name='Тип операции')),
                ('source_type', models.CharField(blank=True, default='', help_text='Тип источника: campaign_channel, payout, manual, system', max_length=50, verbose_name='Тип источника')),
                ('source_id', models.UUIDField(blank=True, help_text='UUID связанного объекта (CampaignChannel, Payout, etc.)', null=True, verbose_name='ID источника')),
                ('description', models.TextField(blank=True, default='', help_text='Описание операции для audit trail', verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Доп. данные (impressions, cpm, и т.д.)', verbose_name='Метаданные')),
                ('account', models.ForeignKey(help_text='Счёт, по которому проводится запись', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.account', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Запись в главной книге',
                'verbose_name_plural': 'Записи в главной книге',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='core_ledger_account_8c2c5a_idx'), models.Index(fields=['transaction_id'], name='core_ledger_transac_94b06a_idx'), models.Index(fields=['transaction_type', '-created_at'], name='core_ledger_transac_b792a8_idx'), models.Index(fields=['source_type', 'source_id'], name='core_ledger_source__e2ad98_idx')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('ledgerentry'), models.Model),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['channel', 'account_type'], name='core_accoun_channel_20a478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('channel', 'account_type', 'currency')},
        ),
    ]
