# Generated by Django 5.2.7 on 2025-11-19 13:31

from django.db import migrations
from decimal import Decimal
import uuid


def migrate_channeltransaction_to_double_entry(apps, schema_editor):
    """
    CHANGE: Data migration from ChannelTransaction to double-entry ledger
    WHY: Migrate existing transaction data to new Account/LedgerEntry system
    REF: Financial system migration 2025-11-19

    Converts old ChannelTransaction records to proper double-entry bookkeeping.
    """
    ChannelTransaction = apps.get_model('core', 'ChannelTransaction')
    Account = apps.get_model('core', 'Account')
    LedgerEntry = apps.get_model('core', 'LedgerEntry')
    Channel = apps.get_model('core', 'Channel')

    # Process transactions by channel for better organization
    from collections import defaultdict
    channel_txns = defaultdict(list)

    for txn in ChannelTransaction.objects.all().order_by('created_at'):
        channel_txns[txn.channel_id].append(txn)

    print(f"\nMigrating {ChannelTransaction.objects.count()} transactions from {len(channel_txns)} channels...")

    migrated_count = 0
    error_count = 0

    for channel_id, txns in channel_txns.items():
        try:
            channel = Channel.objects.get(id=channel_id)
            currency = getattr(txns[0], 'currency', 'RUB')

            # Create accounts for this channel
            cash_account, _ = Account.objects.get_or_create(
                channel=channel,
                account_type='cash',
                defaults={'currency': currency}
            )
            frozen_account, _ = Account.objects.get_or_create(
                channel=channel,
                account_type='frozen',
                defaults={'currency': currency}
            )
            revenue_account, _ = Account.objects.get_or_create(
                channel=channel,
                account_type='revenue',
                defaults={'currency': currency}
            )
            expense_account, _ = Account.objects.get_or_create(
                channel=channel,
                account_type='expense',
                defaults={'currency': currency}
            )

            # Convert each transaction
            for txn in txns:
                tx_id = uuid.uuid4()
                amount = abs(txn.amount)

                if amount == 0:
                    continue

                # Map transaction types to double-entry
                if txn.transaction_type == 'income':
                    # Debit CASH, Credit REVENUE
                    LedgerEntry.objects.create(
                        account=cash_account,
                        amount=amount,
                        entry_type='debit',
                        transaction_id=tx_id,
                        transaction_type='income',
                        description=txn.description or f"Income {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    LedgerEntry.objects.create(
                        account=revenue_account,
                        amount=amount,
                        entry_type='credit',
                        transaction_id=tx_id,
                        transaction_type='income',
                        description=txn.description or f"Income {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    migrated_count += 1

                elif txn.transaction_type == 'freeze':
                    # Debit FROZEN, Credit CASH
                    LedgerEntry.objects.create(
                        account=frozen_account,
                        amount=amount,
                        entry_type='debit',
                        transaction_id=tx_id,
                        transaction_type='freeze',
                        description=txn.description or f"Freeze {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    LedgerEntry.objects.create(
                        account=cash_account,
                        amount=amount,
                        entry_type='credit',
                        transaction_id=tx_id,
                        transaction_type='freeze',
                        description=txn.description or f"Freeze {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    migrated_count += 1

                elif txn.transaction_type == 'unfreeze':
                    # Debit CASH, Credit FROZEN
                    LedgerEntry.objects.create(
                        account=cash_account,
                        amount=amount,
                        entry_type='debit',
                        transaction_id=tx_id,
                        transaction_type='unfreeze',
                        description=txn.description or f"Unfreeze {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    LedgerEntry.objects.create(
                        account=frozen_account,
                        amount=amount,
                        entry_type='credit',
                        transaction_id=tx_id,
                        transaction_type='unfreeze',
                        description=txn.description or f"Unfreeze {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    migrated_count += 1

                elif txn.transaction_type == 'payout':
                    # Debit EXPENSE, Credit CASH
                    LedgerEntry.objects.create(
                        account=expense_account,
                        amount=amount,
                        entry_type='debit',
                        transaction_id=tx_id,
                        transaction_type='payout',
                        description=txn.description or f"Payout {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    LedgerEntry.objects.create(
                        account=cash_account,
                        amount=amount,
                        entry_type='credit',
                        transaction_id=tx_id,
                        transaction_type='payout',
                        description=txn.description or f"Payout {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    migrated_count += 1

                elif txn.transaction_type == 'commission':
                    # Debit EXPENSE, Credit CASH
                    LedgerEntry.objects.create(
                        account=expense_account,
                        amount=amount,
                        entry_type='debit',
                        transaction_id=tx_id,
                        transaction_type='commission',
                        description=txn.description or f"Commission {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    LedgerEntry.objects.create(
                        account=cash_account,
                        amount=amount,
                        entry_type='credit',
                        transaction_id=tx_id,
                        transaction_type='commission',
                        description=txn.description or f"Commission {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    migrated_count += 1

                elif txn.transaction_type == 'refund':
                    # Debit CASH, Credit EXPENSE (reverse of payout)
                    LedgerEntry.objects.create(
                        account=cash_account,
                        amount=amount,
                        entry_type='debit',
                        transaction_id=tx_id,
                        transaction_type='refund',
                        description=txn.description or f"Refund {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    LedgerEntry.objects.create(
                        account=expense_account,
                        amount=amount,
                        entry_type='credit',
                        transaction_id=tx_id,
                        transaction_type='refund',
                        description=txn.description or f"Refund {amount}",
                        source_type=txn.source_type or '',
                        source_id=txn.source_id,
                        metadata=txn.metadata or {},
                        created_at=txn.created_at,
                        updated_at=txn.updated_at
                    )
                    migrated_count += 1

                elif txn.transaction_type == 'adjustment':
                    # Adjustment can be either direction
                    if txn.amount > 0:
                        # Positive adjustment: Debit CASH, Credit REVENUE
                        LedgerEntry.objects.create(
                            account=cash_account,
                            amount=amount,
                            entry_type='debit',
                            transaction_id=tx_id,
                            transaction_type='adjustment',
                            description=txn.description or f"Adjustment +{amount}",
                            source_type=txn.source_type or '',
                            source_id=txn.source_id,
                            metadata=txn.metadata or {},
                            created_at=txn.created_at,
                            updated_at=txn.updated_at
                        )
                        LedgerEntry.objects.create(
                            account=revenue_account,
                            amount=amount,
                            entry_type='credit',
                            transaction_id=tx_id,
                            transaction_type='adjustment',
                            description=txn.description or f"Adjustment +{amount}",
                            source_type=txn.source_type or '',
                            source_id=txn.source_id,
                            metadata=txn.metadata or {},
                            created_at=txn.created_at,
                            updated_at=txn.updated_at
                        )
                    else:
                        # Negative adjustment: Debit EXPENSE, Credit CASH
                        LedgerEntry.objects.create(
                            account=expense_account,
                            amount=amount,
                            entry_type='debit',
                            transaction_id=tx_id,
                            transaction_type='adjustment',
                            description=txn.description or f"Adjustment -{amount}",
                            source_type=txn.source_type or '',
                            source_id=txn.source_id,
                            metadata=txn.metadata or {},
                            created_at=txn.created_at,
                            updated_at=txn.updated_at
                        )
                        LedgerEntry.objects.create(
                            account=cash_account,
                            amount=amount,
                            entry_type='credit',
                            transaction_id=tx_id,
                            transaction_type='adjustment',
                            description=txn.description or f"Adjustment -{amount}",
                            source_type=txn.source_type or '',
                            source_id=txn.source_id,
                            metadata=txn.metadata or {},
                            created_at=txn.created_at,
                            updated_at=txn.updated_at
                        )
                    migrated_count += 1

        except Exception as e:
            print(f"Error migrating channel {channel_id}: {e}")
            error_count += 1
            continue

    print(f"✅ Migration completed: {migrated_count} transactions migrated, {error_count} errors")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: delete all ledger entries and accounts
    WARNING: This will delete all double-entry ledger data!
    """
    LedgerEntry = apps.get_model('core', 'LedgerEntry')
    Account = apps.get_model('core', 'Account')

    print("\n⚠️  Reversing migration: deleting all ledger entries and accounts...")

    entry_count = LedgerEntry.objects.count()
    account_count = Account.objects.count()

    LedgerEntry.objects.all().delete()
    Account.objects.all().delete()

    print(f"✅ Deleted {entry_count} ledger entries and {account_count} accounts")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_add_double_entry_ledger'),
    ]

    operations = [
        migrations.RunPython(
            migrate_channeltransaction_to_double_entry,
            reverse_migration
        ),
    ]
