# Generated by Django 4.2.26 on 2025-11-19 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_migrate_channeltransaction_to_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPlanGeneration',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('success', 'Готов'), ('error', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('file', models.FileField(blank=True, null=True, upload_to='media_plans/', verbose_name='Файл')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('rows_count', models.PositiveIntegerField(default=0, verbose_name='Количество строк')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Краткая сводка по кампаниям/стоимости', verbose_name='Метаданные')),
                ('campaigns', models.ManyToManyField(related_name='media_plan_generations', to='core.campaign', verbose_name='Кампании')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_plan_generations', to=settings.AUTH_USER_MODEL, verbose_name='Кем запрошен')),
            ],
            options={
                'verbose_name': 'Генерация медиаплана',
                'verbose_name_plural': 'Генерации медиапланов',
                'ordering': ['-created_at'],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('mediaplangeneration'), models.Model),
        ),
    ]
