"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path


from .app_settings import AppSettings

app_settings = AppSettings()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = app_settings.SECRET_KEY

# Enable/Disable DEBUG Mode
DEBUG = app_settings.DEBUG
ALLOWED_HOSTS = [
    '.localhost',
    '127.0.0.1',
    '.telewin.online',
    '51.250.45.63',
    '91.108.5.74',
] if not DEBUG else ['*']

# Add here your deployment HOSTS
CSRF_TRUSTED_ORIGINS = [
    'https://*.telewin.online',
    'http://localhost',
    'http://localhost:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8001',
]


X_FRAME_OPTIONS = "SAMEORIGIN"

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "drf_yasg",
    'rest_framework',
    'rest_framework.authtoken',
    'django_celery_beat',
    'django_celery_results',
    'core',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.middlewares.IPMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# to allow TG-login
SECURE_CROSS_ORIGIN_OPENER_POLICY='same-origin-allow-popups'
###
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

ROOT_URLCONF = "web_app.urls"

AUTH_USER_MODEL = 'core.User'

HOME_TEMPLATES = os.path.join(BASE_DIR, 'templates')

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [HOME_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "web_app.wsgi.application"

DATABASES = {
  'default': {
    'ENGINE'  : 'django.db.backends.' + app_settings.DB_ENGINE,
    'NAME'    : app_settings.DB_NAME,
    'USER'    : app_settings.DB_USERNAME,
    'PASSWORD': app_settings.DB_PASS,
    'HOST'    : app_settings.DB_HOST,
    'PORT'    : app_settings.DB_PORT,
    },
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'staticfiles'),
# )

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_REDIRECT_URL = '/core/campaignchannel/'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# django setting.
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
        # 'rest_framework.permissions.DjangoModelPermissions',
    ],

    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     # 'rest_framework.throttling.UserRateThrottle'
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     "anon": "5/h",
    #     'user': '1000/h',
    # }

}




CSRF_COOKIE_HTTPONLY = False

# swagger
SWAGGER_SETTINGS = {
    'VALIDATOR_URL': 'http://localhost:8189',
}


# Celery Configuration Options
CELERY_TIMEZONE = "UTC"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'


JAZZMIN_SETTINGS = {
    "welcome_sign": "Welcome to the Telewin Admin, Please Login.",
    "site_title": "Telewin Admin",
    "site_header": "Telewin",
    "site_brand": "Telewin Administration",
    "show_ui_builder": True,
    "related_modal_active": True,
    "custom_css": 'custom/main.css',
    "custom_js": 'custom/main.js',
    "site_logo_classes": "img",
    "icons": {
        "core.User": "fas fa-user-alt",
        "core.Message": "fas fa-edit",
        "core.CampaignChannel": "fas fa-chart-line",
        "core.Campaign": "fas fa-compass",
        "core.ChannelAdmin": "fas fa-glasses",
        "core.Channel": "fab fa-telegram-plane",
    },

    'site_logo': 'custom/1.png',
    "site_icon": 'custom/fav.png',
    "hide_apps": [
        'django_celery_results',
        'authtoken',
    ],
    'hide_models': [
        'django_celery_beat.clockedschedule',
        'django_celery_beat.solarschedule',
        'core.messagelink'
    ],
    "topmenu_links": [
        {"model": 'core.Campaign'},
        {"model": 'core.Channel'},
        {"model": 'core.Message'},
        {"model": 'core.ChanelAdmin'},
        {"model": 'core.CampaignChannel'},
    ],
    # "language_chooser": True
}

JAZZMIN_UI_TWEAKS = {}

#
# JAZZMIN_SETTINGS = {
#     # title of the window (Will default to current_admin_site.site_title if absent or None)
#     "site_title": "Telewin Admin",
#
#     # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
#     "site_header": "Telewin",
#
#     # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
#
#     # Logo to use for your site, must be present in static files, used for brand on top left
#     # "site_logo": "books/img/logo.png",
#
#     # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
#     # "login_logo": None,
#
#     # Logo to use for login form in dark themes (defaults to login_logo)
#     # "login_logo_dark": None,
#
#     # CSS classes that are applied to the logo above
#
#     # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
#     "site_icon": None,
#
#     # Welcome text on the login screen
#     "welcome_sign": "Welcome to the Telewin Admin",
#
#     # Copyright on the footer
#     # "copyright": "Acme Library Ltd",
#
#     # List of model admins to search from the search bar, search bar omitted if excluded
#     # If you want to use a single search field you dont need to use a list, you can use a simple string
#     "search_model": ["auth.User", "auth.Group"],
#
#     # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
#     "user_avatar": None,
#
#     ############
#     # Top Menu #
#     ############
#
#     # Links to put along the top menu
#     "topmenu_links": [
#         # Url that gets reversed (Permissions can be added)
#         {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
#         # external url that opens in a new window (Permissions can be added)
#         {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
#         # model admin to link to (Permissions checked against model)
#         {"model": "auth.User"},
#         # App with dropdown menu to all its models pages (Permissions checked against models)
#         # {"app": "books"},
#     ],
#
#     #############
#     # User Menu #
#     #############
#
#     # Additional links to include in the user menu on the top right ("app" url type is not allowed)
#     "usermenu_links": [
#         {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
#         {"model": "auth.user"}
#     ],
#
#     #############
#     # Side Menu #
#     #############
#
#     # Whether to display the side menu
#     "show_sidebar": True,
#
#     # Whether to aut expand the menu
#     "navigation_expanded": True,
#
#     # Hide these apps when generating side menu e.g (auth)
#     "hide_apps": [],
#
#     # Hide these models when generating side menu (e.g auth.user)
#     "hide_models": [],
#
#     # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
#     "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
#
#     # Custom links to append to app groups, keyed on app name
#     # "custom_links": {
#     #     "books": [{
#     #         "name": "Make Messages",
#     #         "url": "make_messages",
#     #         "icon": "fas fa-comments",
#     #         "permissions": ["books.view_book"]
#     #     }]
#     # },
#
#     # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
#     # for the full list of 5.13.0 free icon classes
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#     },
#     # Icons that are used when one is not manually specified
#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-circle",
#
#     #################
#     # Related Modal #
#     #################
#     # Use modals instead of popups
#     "related_modal_active": False,
#
#     #############
#     # UI Tweaks #
#     #############
#     # Relative paths to custom CSS/JS scripts (must be present in static files)
#     "custom_css": None,
#     "custom_js": None,
#     # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
#     "use_google_fonts_cdn": True,
#     # Whether to show the UI customizer on the sidebar
#     "show_ui_builder": False,
#
#     ###############
#     # Change view #
#     ###############
#     # Render out the change view as a single form, or in tabs, current options are
#     # - single
#     # - horizontal_tabs (default)
#     # - vertical_tabs
#     # - collapsible
#     # - carousel
#     "changeform_format": "single",
#     # override change forms on a per modeladmin basis
#     "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
#     # Add a language dropdown into the admin
#     # "language_chooser": True,
# }

# handler404 = '404.html'
# handler500 = '500.html'
USE_X_FORWARDED_HOST = True

IP_BLOCKLIST = [
    '188.212.125.110',
    '143.42.206.215',
]
