"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

from django.utils.safestring import mark_safe

from .app_settings import AppSettings

app_settings = AppSettings()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = app_settings.SECRET_KEY

# Enable/Disable DEBUG Mode
DEBUG = app_settings.DEBUG
ALLOWED_HOSTS = (
    [
        ".localhost",
        "127.0.0.1",
        "web-app",
        ".telewin.online",
        ".wpmix.net",
        "telewin.wpmix.net",
        "51.250.45.63",
        "91.108.5.74",
    ]
    if not DEBUG
    else ["*"]
)

# Add here your deployment HOSTS
CSRF_TRUSTED_ORIGINS = [
    "https://*.telewin.online",
    "https://*.wpmix.net",
    "https://telewin.wpmix.net",
    "http://telewin.wpmix.net",
    "http://localhost",
    "http://localhost:8000",
    "http://localhost:8001",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:8001",
]


X_FRAME_OPTIONS = "SAMEORIGIN"

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "drf_yasg",
    "rest_framework",
    "rest_framework.authtoken",
    "django_celery_beat",
    "django_celery_results",
    "core",
    "django_prometheus",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "core.middlewares.DatabaseMigrationCheckMiddleware",  # Должен быть первым для перехвата ошибок БД
    "django.middleware.security.SecurityMiddleware",
    # "core.middlewares.IPMiddleware",
    # "core.middlewares.PathRestrictMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]


# to allow TG-login
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
###
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

ROOT_URLCONF = "web_app.urls"

AUTH_USER_MODEL = "core.User"

HOME_TEMPLATES = os.path.join(BASE_DIR, "templates")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [HOME_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "web_app.context_processors.telewin_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "web_app.wsgi.application"

default_engine = (
    "django.db.backends.sqlite3"
    if app_settings.DB_ENGINE == "sqlite3"
    else "django_prometheus.db.backends." + app_settings.DB_ENGINE
)

DATABASES = {
    "default": {
        "ENGINE": default_engine,
        "NAME": app_settings.DB_NAME,
        "USER": app_settings.DB_USERNAME,
        "PASSWORD": app_settings.DB_PASS,
        "HOST": app_settings.DB_HOST,
        "PORT": app_settings.DB_PORT,
        "TEST": {
            "NAME": "app_test_db",
            "TEMPLATE": "template0",
        },
    },
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_DIRS = (
    BASE_DIR / "static",
    BASE_DIR / "core" / "static",
)

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_REDIRECT_URL = "/core/campaignchannel/"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# cash
CACHES = {
    "default": {
        "BACKEND": "django_prometheus.cache.backends.redis.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.db.backends": {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        }
    },


}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
        # 'rest_framework.permissions.DjangoModelPermissions',
    ],
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     # 'rest_framework.throttling.UserRateThrottle'
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     "anon": "5/h",
    #     'user': '1000/h',
    # }
}


CSRF_COOKIE_HTTPONLY = False

# swagger
SWAGGER_SETTINGS = {
    "VALIDATOR_URL": "http://localhost:8189",
}


# Celery Configuration Options
CELERY_TIMEZONE = "Europe/Moscow"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "default"

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    'check-scheduled-messages-every-minute': {
        'task': 'core.tasks.check_and_publish_scheduled_messages',
        'schedule': 60.0,  # Каждую минуту
    },
}

LOGIN_WELCOME_MSG = """
<div class="text-center">
<p>&#128171; Добро пожаловать в ТЕЛЕВИН – платформу пассивного дохода на рекламе в Telegram! &#128171;</p>
<a href='https://telewin.online/'>Web-site - https://telewin.online/ </a><br />
<a href='https://t.me/telewin_online'>Канал – https://t.me/telewin_online</a><br />
<p> Если вы являетесь администратором канала, используйте кнопку входа через Telegram.</p>
</div>
"""
JAZZMIN_SETTINGS = {
    "welcome_sign": mark_safe(LOGIN_WELCOME_MSG),
    "site_title": "Telewin Admin",
    "site_header": "Telewin",
    "show_sidebar": True,
    "site_brand": "Telewin Administration",
    "show_ui_builder": False,
    "related_modal_active": True,
    "custom_css": "custom/main.css",
    "custom_js": "custom/main.js",
    "site_logo_classes": "img",
    "icons": {
        "core.User": "fas fa-user-alt",
        "core.Message": "fas fa-edit",
        "core.CampaignChannel": "fas fa-chart-line",
        "core.Campaign": "fas fa-compass",
        "core.ChannelAdmin": "fas fa-glasses",
        "core.Channel": "fab fa-telegram-plane",
        "core.LegalEntity": "fas fa-building",
        "core.ChannelTransaction": "fas fa-coins",
        "core.Payout": "fas fa-money-bill-wave",
        "core.MessagePreviewToken": "fas fa-eye",
        "core.UserLoginToken": "fas fa-key",
        "core.ChannelPublicationSlot": "fas fa-clock",
    },
    "site_logo": "custom/logo.gif",
    "site_icon": "custom/fav.png",
    "hide_apps": [
        "django_celery_results",
        "authtoken",
    ],
    "hide_models": [
        "django_celery_beat.clockedschedule",
        "django_celery_beat.solarschedule",
        "core.user",
        "core.messagelink",
        "auth.group",
        "django_celery_beat.crontabschedule",
        "django_celery_beat.periodictask",
        "django_celery_beat.intervalschedule",
    ],
    "custom_links": {
        "core": [
            {
                "name": "Пользователи",
                "url": "/core/user",
                "icon": "fas fa-user-alt",
                'permissions': ["auth.add_user"],
            },
            {
                "name": "О Компании",
                "url": "/api/about",
                "icon": "fa-solid fa-building",
            },

        ],
        "auth": [
            {
                "name": "Группы",
                "url": "/auth/group/",
                "icon": "fa-solid fa-user-group",
                'permissions': ["auth.add_user"],
            },
        ],
        "django_celery_beat": [
            {
                "name": "Crontab",
                "url": "/django_celery_beat/crontabschedule/",
                "icon": "fa-solid fa-clock",
                'permissions': ["auth.add_user"],
            },
            {
                "name": "Интервалы",
                "url": "/django_celery_beat/intervalschedule/",
                "icon": "fa-solid fa-repeat",
                'permissions': ["auth.add_user"],
            },

            {
                "name": "Периодические задачи",
                "url": "/django_celery_beat/periodictask/",
                "icon": "fa-solid fa-list-check",
                'permissions': ["auth.add_user"],
            },

        ],
    },
    # "language_chooser": True
    "order_with_respect_to": [
        "core.channeladmin",
        "core.campaign",
        "core.channel",
        "core.message",
        "core.user",
    ]
    #     "core.campaignchannel",
    #     'django_celery_beat.crontabschedule',
    #     'django_celery_beat.intervalschedule',
    #     'django_celery_beat.periodictask'
    # ],
}



# handler404 = '404.html'
# handler500 = '500.html'
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Для Cloudflare Flexible SSL

IP_BLOCKLIST = [
    "188.212.125.110",
    "143.42.206.215",
    "93.174.93.12",
    "95.128.157.155",
    "149.50.96.114",
    "40.76.124.166",
    "65.49.1.66",
]

# Locale
LOCALE_PATHS = [
    BASE_DIR / "locale",
]
